import type { NextPage } from "next";
import Head from "next/head";
import Sidebar from "../components/sidebar/sidebar.component";
import Feed from "../components/feed/feed.component";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name={"discription"} content={"Generated by create-next-app"} />
        <link rel={"icon"} href={"/favicon.ico"} />
      </Head>

      <main className={"flex min-h-screen max-w-7xl mx-auto"}>
        <Sidebar />
        <Feed />
      </main>
    </>
  );
};

export default Home;
